/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard.index'
import { Route as DashboardDashboardWalletRouteImport } from './routes/_dashboard/dashboard.wallet'
import { Route as DashboardDashboardTailorsRouteImport } from './routes/_dashboard/dashboard.tailors'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard.settings'
import { Route as DashboardDashboardExploreRouteImport } from './routes/_dashboard/dashboard.explore'
import { Route as DashboardDashboardCreateRouteImport } from './routes/_dashboard/dashboard.create'
import { Route as DashboardDashboardOrdersIndexRouteImport } from './routes/_dashboard/dashboard.orders.index'
import { Route as DashboardDashboardOrdersOrderIdRouteImport } from './routes/_dashboard/dashboard.orders.$orderId'
import { Route as DashboardDashboardOrdersOrderIdPayRouteImport } from './routes/_dashboard/dashboard.orders.$orderId.pay'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardWalletRoute =
  DashboardDashboardWalletRouteImport.update({
    id: '/dashboard/wallet',
    path: '/dashboard/wallet',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardTailorsRoute =
  DashboardDashboardTailorsRouteImport.update({
    id: '/dashboard/tailors',
    path: '/dashboard/tailors',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardExploreRoute =
  DashboardDashboardExploreRouteImport.update({
    id: '/dashboard/explore',
    path: '/dashboard/explore',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardCreateRoute =
  DashboardDashboardCreateRouteImport.update({
    id: '/dashboard/create',
    path: '/dashboard/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardOrdersIndexRoute =
  DashboardDashboardOrdersIndexRouteImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardOrdersOrderIdRoute =
  DashboardDashboardOrdersOrderIdRouteImport.update({
    id: '/dashboard/orders/$orderId',
    path: '/dashboard/orders/$orderId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardOrdersOrderIdPayRoute =
  DashboardDashboardOrdersOrderIdPayRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => DashboardDashboardOrdersOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/create': typeof DashboardDashboardCreateRoute
  '/dashboard/explore': typeof DashboardDashboardExploreRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/tailors': typeof DashboardDashboardTailorsRoute
  '/dashboard/wallet': typeof DashboardDashboardWalletRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/orders/$orderId': typeof DashboardDashboardOrdersOrderIdRouteWithChildren
  '/dashboard/orders/': typeof DashboardDashboardOrdersIndexRoute
  '/dashboard/orders/$orderId/pay': typeof DashboardDashboardOrdersOrderIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/create': typeof DashboardDashboardCreateRoute
  '/dashboard/explore': typeof DashboardDashboardExploreRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/dashboard/tailors': typeof DashboardDashboardTailorsRoute
  '/dashboard/wallet': typeof DashboardDashboardWalletRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/orders/$orderId': typeof DashboardDashboardOrdersOrderIdRouteWithChildren
  '/dashboard/orders': typeof DashboardDashboardOrdersIndexRoute
  '/dashboard/orders/$orderId/pay': typeof DashboardDashboardOrdersOrderIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_dashboard/dashboard/create': typeof DashboardDashboardCreateRoute
  '/_dashboard/dashboard/explore': typeof DashboardDashboardExploreRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/_dashboard/dashboard/tailors': typeof DashboardDashboardTailorsRoute
  '/_dashboard/dashboard/wallet': typeof DashboardDashboardWalletRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/orders/$orderId': typeof DashboardDashboardOrdersOrderIdRouteWithChildren
  '/_dashboard/dashboard/orders/': typeof DashboardDashboardOrdersIndexRoute
  '/_dashboard/dashboard/orders/$orderId/pay': typeof DashboardDashboardOrdersOrderIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/create'
    | '/dashboard/explore'
    | '/dashboard/settings'
    | '/dashboard/tailors'
    | '/dashboard/wallet'
    | '/dashboard/'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/'
    | '/dashboard/orders/$orderId/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/create'
    | '/dashboard/explore'
    | '/dashboard/settings'
    | '/dashboard/tailors'
    | '/dashboard/wallet'
    | '/dashboard'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders'
    | '/dashboard/orders/$orderId/pay'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/signup'
    | '/_dashboard/dashboard/create'
    | '/_dashboard/dashboard/explore'
    | '/_dashboard/dashboard/settings'
    | '/_dashboard/dashboard/tailors'
    | '/_dashboard/dashboard/wallet'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/orders/$orderId'
    | '/_dashboard/dashboard/orders/'
    | '/_dashboard/dashboard/orders/$orderId/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/wallet': {
      id: '/_dashboard/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardDashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/tailors': {
      id: '/_dashboard/dashboard/tailors'
      path: '/dashboard/tailors'
      fullPath: '/dashboard/tailors'
      preLoaderRoute: typeof DashboardDashboardTailorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/explore': {
      id: '/_dashboard/dashboard/explore'
      path: '/dashboard/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardDashboardExploreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/create': {
      id: '/_dashboard/dashboard/create'
      path: '/dashboard/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardDashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/orders/': {
      id: '/_dashboard/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardDashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/orders/$orderId': {
      id: '/_dashboard/dashboard/orders/$orderId'
      path: '/dashboard/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof DashboardDashboardOrdersOrderIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/orders/$orderId/pay': {
      id: '/_dashboard/dashboard/orders/$orderId/pay'
      path: '/pay'
      fullPath: '/dashboard/orders/$orderId/pay'
      preLoaderRoute: typeof DashboardDashboardOrdersOrderIdPayRouteImport
      parentRoute: typeof DashboardDashboardOrdersOrderIdRoute
    }
  }
}

interface DashboardDashboardOrdersOrderIdRouteChildren {
  DashboardDashboardOrdersOrderIdPayRoute: typeof DashboardDashboardOrdersOrderIdPayRoute
}

const DashboardDashboardOrdersOrderIdRouteChildren: DashboardDashboardOrdersOrderIdRouteChildren =
  {
    DashboardDashboardOrdersOrderIdPayRoute:
      DashboardDashboardOrdersOrderIdPayRoute,
  }

const DashboardDashboardOrdersOrderIdRouteWithChildren =
  DashboardDashboardOrdersOrderIdRoute._addFileChildren(
    DashboardDashboardOrdersOrderIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardCreateRoute: typeof DashboardDashboardCreateRoute
  DashboardDashboardExploreRoute: typeof DashboardDashboardExploreRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardTailorsRoute: typeof DashboardDashboardTailorsRoute
  DashboardDashboardWalletRoute: typeof DashboardDashboardWalletRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardOrdersOrderIdRoute: typeof DashboardDashboardOrdersOrderIdRouteWithChildren
  DashboardDashboardOrdersIndexRoute: typeof DashboardDashboardOrdersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardCreateRoute: DashboardDashboardCreateRoute,
  DashboardDashboardExploreRoute: DashboardDashboardExploreRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardTailorsRoute: DashboardDashboardTailorsRoute,
  DashboardDashboardWalletRoute: DashboardDashboardWalletRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardOrdersOrderIdRoute:
    DashboardDashboardOrdersOrderIdRouteWithChildren,
  DashboardDashboardOrdersIndexRoute: DashboardDashboardOrdersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
